name: file CI

on:
  push:
     branches: [master]
  pull_request: 
     branches: [master]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: uses Node.js ${{ matrix.version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.version }}
      - run: npm install --legacy-peer-deps   
       