name: Continuous Integration and Deployment
on:
  push:
     branches: [master]
  pull_request: 
     branches: [master]

jobs:
  defaults:
    steps:
     run:
       working-directory: ./dirto
  build:
    runs-on: self-hosted
    steps:
      - name: Display contents of directory before checkout
        run: |
          echo "Before checkout:"
          ls -la

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display contents of directory after checkout
        run: |
          echo "After checkout:"
          ls -la

      - name: Uses Node.js ${{ matrix.version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.version }}

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps   

      - name: Reload and save PM2 configuration
        run: |
          pm2 reload ecosystem.config.js
          pm2 save 
